title: Scala-Poland
author: Waldemar Wosiński
email: kastoestoramadus+scalapoland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ogólno-polska grupa entuzjastów Scali.

twitter_username: singpoo
github_username:  kastoestoramadus
google_analytics: "UA-123554052-2"

sass:
    style: compressed
