title: Scala Poland - slack group, IT, language, local groups, Polish companies
author: Waldemar Wosiński
email: kastoestoramadus+scalapoland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ogólnopolska grupa entuzjastów Scali.

twitter_username: singpoo
github_username:  kastoestoramadus
google_analytics: "UA-123554052-2"
disqus:
  shortname: "scala-poland"

sass:
    style: compressed
